name: prod

on: 
  push: 
    branches: 
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: "Install PNPM"
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.2 

      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: "Install dependencies"
        run: pnpm install

      - name: Run linter
        run: pnpm run lint
        
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
